
import numpy as np
import matplotlib.pyplot as plt


def simulate(r, a0, n_steps):
    """array a[0..n_steps] generated by a[n+1] = r*a[n] - 1000."""
    a = np.empty(n_steps + 1)
    a[0] = a0
    for n in range(n_steps):
        a[n + 1] = r * a[n] - 1000
    return a

def main():

    scenarios = [
        ("(i)   r = 1.05, a0 = 25,000", 1.05, 25000, 40),
        ("(ii)  r = 1.08, a0 = 8,000", 1.08, 8000, 40),
        ("(iii) r = 1.01, a0 = 100,000", 1.01, 100000, 40),
        ("(iv)  r = 0.98, a0 = 100,000", 0.98, 100000, 200),
    ]

    fig, axes = plt.subplots(2, 2, figsize=(12, 9))
    axes = axes.ravel()

    for ax, (label, r, a0, n_steps) in zip(axes, scenarios):
        a = simulate(r, a0, n_steps)
        n = np.arange(n_steps + 1)

        # fixed point a* = 1000 / (r - 1)  (for r != 1)
        b_star = 1000 / (r - 1)

        ax.plot(n, a, marker='o', markersize=3, linewidth=1, color='tab:blue',
                label='a[n] (numerical)')
        ax.axhline(0, color='red', linestyle='--', linewidth=1, label='Zero balance')
        ax.axhline(b_star, color='green', linestyle=':', linewidth=1,
                label=f'Fixed point a* = {b_star:,.0f}')

        ax.set_title(label)
        ax.set_xlabel('Period n')
        ax.set_ylabel('Account balance a[n]')
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)

       
        print(f"\n{label}")
        print(f"  Fixed point a* = 1000/(r-1) = {b_star:,.2f}")
        print(f"  a[0]  = {a[0]:,.2f}")
        print(f"  a[5]  = {a[5]:,.2f}")
        print(f"  a[10] = {a[10]:,.2f}")
        print(f"  a[{n_steps}] = {a[-1]:,.2f}")

    plt.tight_layout()
    plt.savefig('retirement_savings.png', dpi=150)
    print("\nPlot saved to retirement_savings.png")
if __name__ == "__main__":
    main()