host_name = localhost
#host_name = 0.0.0.0
port = 5566

# db details
website_bot_db_details = postgresql://aisql:Summer%402025@34.145.153.188:5432/aisqldb
min_pool_connects = 1
max_pool_connects = 20
upd_schema = public
log_file_name = website_bot.log


